
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=postgres
  rabbitmq:
    image: rabbitmq:3.11
  swaggerui:
    image: swaggerapi/swagger-ui:v4.18.0
    volumes:
      - ./swagger:/usr/src/swagger
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/usr/src/swagger/swagger.json
    depends_on:
      - app
